version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: pms-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: pms-redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    container_name: pms-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
    image: elasticsearch:8.6.2
    container_name: pms-elasticsearch
    restart: always
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  postgres_data:
